name: PHP Lint

on:
  push:
    branches: [ main, 'fix/*' ]
  pull_request:
    branches: [ main ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PHP -v
        run: php -v
      - name: Lint PHP files
        run: |
          set -e
          find . -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l
